// Generated by gencpp from file widowx_block_manipulation/BlockDetectionFeedback.msg
// DO NOT EDIT!


#ifndef WIDOWX_BLOCK_MANIPULATION_MESSAGE_BLOCKDETECTIONFEEDBACK_H
#define WIDOWX_BLOCK_MANIPULATION_MESSAGE_BLOCKDETECTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace widowx_block_manipulation
{
template <class ContainerAllocator>
struct BlockDetectionFeedback_
{
  typedef BlockDetectionFeedback_<ContainerAllocator> Type;

  BlockDetectionFeedback_()
    {
    }
  BlockDetectionFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BlockDetectionFeedback_

typedef ::widowx_block_manipulation::BlockDetectionFeedback_<std::allocator<void> > BlockDetectionFeedback;

typedef boost::shared_ptr< ::widowx_block_manipulation::BlockDetectionFeedback > BlockDetectionFeedbackPtr;
typedef boost::shared_ptr< ::widowx_block_manipulation::BlockDetectionFeedback const> BlockDetectionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace widowx_block_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "widowx_block_manipulation/BlockDetectionFeedback";
  }

  static const char* value(const ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
;
  }

  static const char* value(const ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlockDetectionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::widowx_block_manipulation::BlockDetectionFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WIDOWX_BLOCK_MANIPULATION_MESSAGE_BLOCKDETECTIONFEEDBACK_H
